### PR TITLE
Triumph Station Port

### PR DESCRIPTION
**Pull request by Smdytb1**

### CODE REVIEW

**Comment by Smdytb1** [comment]
gonna need some mega help with this one bois

**Comment by Smdytb1** [comment]
Going with the pt2 PR because reasons

**Comment by Smdytb1** [comment]
haha, imagine having to reopen this

**Comment by GremlingSS** [comment]
- Error: Z_LEVEL_BEACH: undefined var
- Error: NETWORK_TETHER: undefined var
- Error: /area/tether/elevator: undefined type path
- Error: /area/rnd/miscellaneous_lab: undefined type path
- Error: /area/triumph/surfacebase/lowernortheva: undefined type path
- Error: /area/triumph/surfacebase/lowernortheva/external: undefined type path
- Error: /area/triumph/surfacebase/security/gasstorage: undefined type path
- Error: Z_LEVEL_BEACH: undefined var
- Error: /turf/space/v3b_midpoint: undefined type path
- Error: Z_LEVEL_BEACH: undefined var
- Error: Z_LEVEL_AEROSTAT: undefined var
- Error: Z_LEVEL_FUELDEPOT: undefined var

\033[0;31mCompiling the codebase normally failed. Please review the compile errors and correct them, usually before making your PR.\033[0m
Error: Process completed with exit code 1.

**Comment by GremlingSS** [comment]
OH ONE LAST THING BEFORE YOU DEPLOY IT
LOBBY SCREEN NEEDS CHANGING

**Comment by GremlingSS** [comment]
## UNIT_TEST: !! FAILURE !! [ZAS: Supply Shuttle]: No zones checked.
## UNIT_TEST: !! FAILURE !! [ZAS: Mining Area (Vacuum)]: No zones checked.

Mining area and Supply shuttle no existeroni
ripperoni

**Comment by Smdytb1** [comment]
pulled in off station areas.dm but an area is still an unknown type :)

**Comment by Smdytb1** [comment]
Needs a lot of runtimes fixed, they don't impact gameplay _much_ but it should work even we do merge... except we'll have a broken CI and yeaaaah

**Comment by Smdytb1** [comment]
HAHA, TIME TO SUFFER /S
will revert and re-open a new PR if there are any major issues. otherwise haha, enjoy getting used to a "new" map

**Comment by GremlingSS** [comment]
GOIA STINKS

**Pull request merged**
