### PR TITLE
Fucking map update again

### PR DESCRIPTION
**Pull request by GremlingSS**
reee stop leaving me to do it goia seriously.

this is aimed to do 5 things.
- [x] Adds in and fixes the rest of the other POIs.
- [ ] Add a planet datum for some planets.
- [ ] Check how to force these to be spawned in as a POI.
- [ ] Finished then mayhaps idk?
- [x] Make Goia eat ass.

### CODE REVIEW

**Comment by GremlingSS** [comment]
okay! Maps are added in though we have a few issues.

Main issue being:
round wont start, it's stuck initliasing, I think it's stuck trying to load a certain map so I'm going through and fixing a couple runtimes, though, if anyone wants to pick up on this. I'm currently rewriting the way how POIs are loaded rn and adding in planet datums. if anyone wants to take over that's where I'm at and I'd be very happy if someone were to take over, so if someone wanted to take over, they'd have to message me telling me they're doin that.

**Comment by GremlingSS** [comment]
ah! _class_d.dm might be trying to read incorrect file types and not loading because of it, lemme confirm

**Comment by GremlingSS** [comment]
Okay! So! It was that reason.

Three things needed to be done.

- [ ] Setup the planets to be POIs.
- [ ] Fix issues with overmap using Z level 5 or 4 (which is used as our centcomm admin level)
- [ ] Sort out the lobby screen shit
- [ ] Ligma
- [ ] Sugma

**Comment by Smdytb1** [comment]
Merging this but adding a link to the last few steps needed to complete the port

**Pull request merged**
