### PR TITLE
Updateroni electric boogaloo 2 [MDB IGNORE] [IDB IGNORE]

### PR DESCRIPTION
**Pull request by GremlingSS**
Ye, does it but better and actually works this time, jon verified:tm:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Please put `[IDB IGNORE]` and `[MDB IGNORE]` in your PR title

You crashed the service for everyone else

**Comment by GremlingSS** [comment]
Sorry man!

**Comment by AffectedArc07** [comment]
> Sorry man!

No worries, but IDB ignore as well please

**Comment by AffectedArc07** [comment]
Much obliged

**Comment by GremlingSS** [comment]
👍

**Pull request merged**
