### PR TITLE
Fixes on the map

### PR DESCRIPTION
**Pull request by Dropshotz**
Fixed(not really) the explo shuttle venting itself. You can't control the airlock form outside, but it cycles properly now.
Added RPD to CE office locker
Fixes toxins lab/robotics office missing wires.
Gave the janitor 4 whole buckets
Adds a Cafeteria, replacing the vacant shop
Replaces kitchen maint with a service maint door.
Adds a new vending machine for Cafeteria.

### CODE REVIEW

**Comment by Dropshotz** [comment]
whoops don't merge I did a fucky

**Comment by Dropshotz** [comment]
undid fucky.

**Comment by Dropshotz** [comment]
idk why it fails on the tether I literally did not touch the tether. what the hell.

**Comment by Dropshotz** [comment]
Holy bolognese it finally works.

**Review by Smdytb1 — APPROVED** [review]

**Pull request merged**
